### ISSUE TITLE
[CHORE]: [fj-doc-lib-direct] add useChainId param for chain alias

### ISSUE THREAD

**Issue by fugerit79** [fugerit-org/fj-doc#406]
### Module

fj-doc-mod-lib-direct - API for Direct Document Generation

### Expected Behavior

Create chain alias to resuce ftl templates

### Other information

If `useChainId` is set, it will be used to resolve the chain instead of `chainId`.

```yaml
chainList:  # a template named ${chainId}.ftl must exist in 'templatePath' folder
  - chainId: 'test-doc'
    dataModel:  # inline data model definition
      docTitle: 'Venus Direct Extension - Test Doc'
  - chainId: 'test-doc-json-data-model'
    dataModelJson: 'src/test/resources/data-model/data-model-1.json'  # JSON file data model
    useChainId: 'test-doc'
  - chainId: 'test-doc-yaml-data-model'
    dataModelYaml: 'src/test/resources/data-model/data-model-1.yaml'  # YAML file data model
    useChainId: 'test-doc'`
```
