### ISSUE TITLE
[CHORE]: 'direct' goal + 'add' / 'init' configure support for extra modules

### ISSUE THREAD

**Issue by fugerit79** [fugerit-org/fj-doc#424]
### Module

fj-doc-maven-plugin - Maven plugin to setup new/existing projects and validate freemarker templates

### Expected Behavior

'add' / 'init' goal should add requested modules support

### Other information

Currently the 'addDirectPlugin' parameter will only add handlers supported by 'base' / 'freemarker' modules.

```yaml
handlerList:
  - type: org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlTypeHandlerUTF8
  - type: org.fugerit.java.doc.base.typehandler.markdown.SimpleMarkdownExtTypeHandlerNoCommentsUTF8
  - type: org.fugerit.java.doc.freemarker.asciidoc.FreeMarkerAsciidocTypeHandlerUTF8
```

We want that, if any other modules is selected, the relevante handler support is added to 'venus-direct' execution.

For instance if 'mod-fop' is added , the configuration should be setup to support it too : 

```yaml
handlerList:
  - type: org.fugerit.java.doc.freemarker.html.FreeMarkerHtmlTypeHandlerUTF8
  - type: org.fugerit.java.doc.base.typehandler.markdown.SimpleMarkdownExtTypeHandlerNoCommentsUTF8
  - type: org.fugerit.java.doc.freemarker.asciidoc.FreeMarkerAsciidocTypeHandlerUTF8
  - type: org.fugerit.java.doc.mod.fop.PdfFopTypeHandler
```
